window.COLOR_MAP = {
  den:   { name: "Đen",   hex: "#111111" },
  trang: { name: "Trắng", hex: "#ffffff" },
  nau:   { name: "Nâu",   hex: "#67320cff"},
  xam:   { name: "Xám",   hex: "#9aa0a6" },
  be:    { name: "Be",    hex: "#e8d9c2" },
  do:    { name: "Đỏ",    hex: "#E60012" },
  xanh:  { name: "Xanh",    hex: "#4A90E2" },}

// ===== MOCK DATA SẢN PHẨM (giữ nguyên từ file cũ) =====
window.PRODUCTS = [
  { id: 1, name: "Cadigan", gender: "female", category: "outer", price: 1299000, oldPrice: 1899000,
    colorIds:["be","den","xam"],imagesByColor: { be:"assets/f011.webp",den:"assets/f012.webp",xam:"assets/f013.webp"},images: ["assets/f011.webp","assets/f012.webp","assets/f013.webp"], description: "Chất dạ mềm, giữ ấm hiệu quả. Thiết kế dáng dài tối giản, dễ phối nhiều lớp." },
  { id: 2, name: "Cadigan", gender: "female", category: "outer", price: 699000, oldPrice: 999000,
    colorIds:["xanh","den"],imagesByColor: { xanh:"assets/f021.webp",den:"assets/f023.webp"},images: ["assets/f021.webp","assets/f022.webp","assets/f023.webp"], description: "Len mịn nhẹ, mặc êm và ấm vừa phải. Phù hợp sử dụng hằng ngày." },
  { id: 3, name: "Cadigan", gender: "female", category: "outer", price: 499000,oldPrice: 799000,
    colorIds:["nau","den"],imagesByColor: { nau:"assets/f031.webp",den:"assets/f032.webp"}, images: ["assets/f031.webp","assets/f032.webp"], description: "Chất len co giãn nhẹ, form gọn gàng. Mang lại cảm giác thoải mái khi mặc." },
  { id: 4, name: "Áo Thun", gender: "female", category: "top", price: 249000,oldPrice: 350000,
    colorIds:["trang","xam",],imagesByColor: { trang:"assets/f041.webp",xam:"assets/f042.webp"}, images: ["assets/f041.webp","assets/f042.webp"], description: "Cotton mềm, thoáng khí. Thiết kế basic phù hợp mặc hằng ngày." },
  { id: 5, name: "Quần Short", gender: "female", category: "bottom", price: 199000,oldPrice: 250000,
    colorIds:["be"],images: ["assets/f051.webp","assets/f052.webp"], description: "Chất vải nhẹ, thoải mái khi di chuyển. Dễ phối cho trang phục thường ngày." }, 
  { id: 6, name: "Áo Thun", gender: "female", category: "top", price: 349000,oldPrice: 799000,
    colorIds:["trang","den","be",],imagesByColor: { trang:"assets/f061.webp",den:"assets/f062.webp",be:"assets/f063.webp" }, images: ["assets/f061.webp","assets/f062.webp","assets/f063.webp"], description: "Vải cotton mịn, form vừa vặn. Phù hợp mặc đơn hoặc phối layer." },
  { id: 7, name: "Chân Váy", gender: "female", category: "bottom", price: 449000,oldPrice: 799000,
    colorIds:["xam","den",],imagesByColor: { xam:"assets/f071.webp",den:"assets/f072.webp"}, images: ["assets/f071.webp","assets/f072.webp"], description: "Thiết kế gọn gàng, dễ phối. Phù hợp nhiều hoàn cảnh sử dụng." },
    { id: 8, name: "Áo Thắt Eo", gender: "female", category: "top", price: 899000,oldPrice: 1099000,
    colorIds:["nau","xam","xanh",],imagesByColor: { nau:"assets/f081.webp",xam:"assets/f082.webp",xanh:"assets/f083.webp"}, images: ["assets/f081.webp","assets/f082.webp","assets/f083.webp"], description: "Thiết kế tạo dáng gọn gàng. Chất vải đứng form, mặc thoải mái." },
  { id: 9, name: "Quần Jean", gender: "female", category: "bottom", price: 899000,oldPrice: 1099000,
    colorIds:["be","den"],imagesByColor: { be:"assets/f091.webp", den:"assets/f092.webp"}, images: ["assets/f091.webp","assets/f092.webp"], description: "Jean co giãn nhẹ, form chuẩn. Dễ mặc và linh hoạt trong sinh hoạt hằng ngày." },
    { id: 10, name: "Áo thun", gender: "female", category: "top", price: 249000,oldPrice: 350000,
    colorIds:["den","be",],imagesByColor: { den:"assets/f101.webp",be:"assets/f102.webp"}, images: ["assets/f101.webp","assets/f102.webp"], description: "Áo thun chất cotton mềm. Phù hợp sử dụng hằng ngày." },
  { id: 11, name: "Chân Váy", gender: "female", category: "bottom", price: 599000,oldPrice: 799000,
    colorIds:["den"], images: ["assets/f111.webp"], description: "Kiểu dáng tối giản, dễ kết hợp trang phục. Phù hợp đi làm hoặc đi chơi." },
    { id: 12, name: "Áo Trễ Vai", gender: "female", category: "top", price: 899000,oldPrice: 1099000,
    colorIds:["den"],images: ["assets/f131.webp"], description: "Thiết kế trễ vai nhẹ, tạo cảm giác thoải mái. Chất vải mềm mại." },
  { id: 13, name: "HEATTECH pha cashmere", gender: "female", category: "top", price: 499000,oldPrice: 799000,
    colorIds:["nau","trang", "xam","do","xanh"],imagesByColor: {nau:"assets/f132.avif", trang:"assets/1/white.jpg", xam:"assets/1/darkgrey.jpg",do:"assets/1/red.jpg",xanh: "assets/1/navi.jpg"}
    ,images: ["assets/f132.avif","assets/1/white.jpg","assets/1/darkgrey.jpg","assets/1/red.jpg","assets/1/darkgrey.jpg"], description: "Phong cách tinh tế, ôm dáng, mỏng nhưng sợi vải chặt, co giãn tốt giúp giữ ấm cực tốt với công nghệ HEATTECH độc quyền. " },
  { id: 14, name: "Áo khoác phao ngắn không đường may", gender: "female", category: "outer", price: 999000,oldPrice: 1099000,
    colorIds:["xam"],images: ["assets/f133.avif"], description: "Giữ ấm cho mùa đông với phong cách năng động, tinh tế"},

  { id: 21, name: "Jacket ", gender: "male", category: "outer", price: 799000, oldPrice: 999000,
    colorIds:["den"],    images: ["assets/m51.webp","assets/m52.webp","assets/m53.webp","assets/m54.webp"], description: "Jacket chắn gió tốt, dáng thoải mái. Phù hợp mặc hằng ngày." },
  { id: 22, name: "Sweater", gender: "male", category: "outer", price: 599000,
    colorIds:["nau","den"],imagesByColor: { nau:"assets/m61.webp",den:"assets/m62.webp",},images: ["assets/m61.webp","assets/m62.webp",], description: "Sweater mềm, giữ ấm vừa phải. Dễ phối cho nhiều phong cách." },
  { id: 23, name: "Hoddie-Zip", gender: "male", category: "outer", price: 799000,oldPrice: 1299000,
    colorIds:["xam","den"],imagesByColor: { xam:"assets/m71.webp",den:"assets/m73.webp",}, images: ["assets/m71.webp","assets/m72.webp","assets/m73.webp",], description: "Hoodie khóa kéo tiện lợi. Chất vải ấm, thoải mái khi mặc." },
  { id: 24, name: "Jacket", gender: "male", category: "outer", price: 499000,oldPrice: 799000,
    colorIds:["trang","den","xanh"],imagesByColor: { trang:"assets/m83.webp",den:"assets/m81.webp",xanh:"assets/m82.webp"}, images: ["assets/m83.webp","assets/m81.webp","assets/m82.webp",], description: "Thiết kế nhẹ, dễ mặc. Phù hợp thời tiết mát." },
  { id: 25, name: "Jacket", gender: "male", category: "outer", price: 899000,
    colorIds:["den"],    oldPrice: 1099000, images: ["assets/m91.webp","assets/m92.webp","assets/m93.webp",], description: "Form gọn gàng, thiết kế đơn giản. Dễ sử dụng trong nhiều hoàn cảnh." },
  { id: 26, name: "Áo Thun", gender: "male", category: "top", price: 349000,
    colorIds:["do","den","xanh","xam"],imagesByColor: { do:"assets/m103.webp",den:"assets/m101.webp",xanh:"assets/m102.webp",xam:"assets/m104.webp"},   oldPrice: 1099000, images: ["assets/m103.webp","assets/m101.webp","assets/m102.webp","assets/m104.webp"], description: "Cotton co giãn, thấm hút tốt. Phù hợp mặc cả ngày." },
  { id: 27, name: "Quần Nỉ", gender: "male", category: "bottom", price: 399000,oldPrice: 799000,
    colorIds:["den","trang","xam"],imagesByColor: { den:"assets/m133.webp",trang:"assets/m132.webp",xam:"assets/m131.webp"}, images: ["assets/m133.webp","assets/m132.webp","assets/m131.webp",], description: "Quần nỉ mềm mại, tạo cảm giác thoải mái khi vận động." },
  { id: 28, name: "Sơ Mi", gender: "male", category: "top", price: 549000,oldPrice: 799000,
    colorIds:["nau"], images: ["assets/m121.webp","assets/m122.webp"], description: "Chất vải thoáng, form gọn. Phù hợp đi làm hoặc đi chơi." },
  { id: 29, name: "Áo Thun", gender: "male", category: "top", price: 499000,oldPrice: 899000, 
    colorIds:["den"],images: ["assets/m11.webp","assets/m12.webp"], description: "Áo thun basic, dễ mặc. Phù hợp trang phục thường ngày." },
  { id: 30, name: "Quần Short", gender: "male", category: "bottom", price: 249000,oldPrice: 599000,
    colorIds:["den","be","xam"],imagesByColor: { den:"assets/m21.webp",be:"assets/m22.webp",xam:"assets/m23.webp"}, images: ["assets/m21.webp","assets/m22.webp","assets/m23.webp","assets/m104.webp"], description: "Quần short nhẹ, thoải mái. Phù hợp sinh hoạt và vận động." },
  { id: 31, name: "Sơ Mi", gender: "male", category: "top", price: 749000,oldPrice: 999000,
    colorIds:["be","den"],imagesByColor: { be:"assets/m41.webp",den:"assets/m42.webp"}, images: ["assets/m41.webp","assets/m42.webp"], description: "Thiết kế tối giản, dễ phối. Phù hợp nhiều dịp." },
  { id: 32, name: "Quần Jean", gender: "male", category: "bottom", price: 399000,oldPrice: 599000,
    colorIds:["den","xanh",],imagesByColor: { den:"assets/m31.webp",xanh:"assets/m32.webp"}, images: ["assets/m31.webp","assets/m32.webp"], description: "Jean bền, form chuẩn. Dễ phối cho trang phục hằng ngày." },
  ];
