window.COLOR_MAP = {
  den:   { name: "den",   hex: "#111111" },
  trang: { name: "trang", hex: "#ffffff" },
  nau:   { name: "nau",   hex: "#8b4513" },
  xam:   { name: "xam",   hex: "#9aa0a6" },
  be:    { name: "be",    hex: "#e8d9c2" },
  do:    { name: "do",    hex: "#E60012" },
  xanh:    { name: "xanh",    hex: "#4A90E2" },
};
// ===== MOCK DATA SẢN PHẨM (giữ nguyên từ file cũ) =====
window.PRODUCTS = [
  { id: 1, name: "Cadigan", gender: "female", category: "outer", price: 1299000, oldPrice: 1899000,
    colorIds:["be","den","xam"],    images: ["assets/f11.webp","assets/f12.webp","assets/f13.webp"], description: "Chất dạ cao cấp, ấm áp, dáng dài thanh lịch." },
  { id: 2, name: "Cadigan", gender: "female", category: "outer", price: 699000, oldPrice: 999000,
    colorIds:["xanh","den"],    images: ["assets/f21.webp","assets/f22.webp","assets/f23.webp"], description: "Len mềm mại, màu beige dễ phối đồ." },
  { id: 3, name: "Quần jean ống suông nữ", gender: "female", category: "bottom", price: 799000,
    colorIds:["den","xam","nau"],    images: ["assets/f11.webp","assets/f12.webp"], description: "Form chuẩn, tôn dáng cực đẹp." },
  { id: 4, name: "Áo sơ mi nữ oversized trắng", gender: "female", category: "top", price: 499000, oldPrice: 799000,
    colorIds:["den","xam","nau"],    images: ["assets/f11.webp","assets/f12.webp"], description: "Phong cách basic, chất cotton thoáng mát." },
  { id: 5, name: "Jacket ", gender: "male", category: "outer", price: 1199000, oldPrice: 1699000,
    colorIds:["den","be"],    images: ["assets/m51.webp","assets/m52.webp","assets/m53.webp","assets/m54.webp"], description: "Dáng rộng thoải mái, chất gió cao cấp." },
  { id: 6, name: "Sweater", gender: "male", category: "outer", price: 599000,
    colorIds:["nau","den"],    images: ["assets/m61.webp","assets/m62.webp",], description: "Lịch lãm, dễ phối đồ công sở." },
  { id: 7, name: "Hoddie-Zip", gender: "male", category: "outer", price: 799000,
    colorIds:["xam","den"],    oldPrice: 1099000, images: ["assets/m71.webp","assets/m72.webp","assets/m73.webp",], description: "Co giãn tốt, form slim tôn dáng." },
  { id: 8, name: "Jacket", gender: "male", category: "outer", price: 799000,
    colorIds:["trang","den","xanh"],    oldPrice: 1099000, images: ["assets/m83.webp","assets/m81.webp","assets/m82.webp",], description: "Co giãn tốt, form slim tôn dáng." },
  { id: 9, name: "Jacket", gender: "male", category: "outer", price: 799000,
    colorIds:["den"],    oldPrice: 1099000, images: ["assets/m91.webp","assets/m92.webp","assets/m93.webp",], description: "Co giãn tốt, form slim tôn dáng." },
  { id: 10, name: "Áo Thun", gender: "male", category: "top", price: 799000,
    colorIds:["do","den","xanh","xam"],imagesByColor: { do:"assets/m103.webp",den:"assets/m101.webp",xanh:"assets/m102.webp",xam:"assets/m104.webp"},   oldPrice: 1099000, images: ["assets/m103.webp","assets/m101.webp","assets/m102.webp","assets/m104.webp"], description: "Co giãn tốt, form slim tôn dáng." },
  { id: 11, name: "Quần Nỉ", gender: "male", category: "bottom", price: 799000,colorIds:["den","trang","xam"],    oldPrice: 1099000, images: ["assets/m133.webp","assets/m132.webp","assets/m131.webp",], description: "Co giãn tốt, form slim tôn dáng." },
  { id: 12, name: "Sơ Mi", gender: "male", category: "top", price: 799000,colorIds:["nau"],    oldPrice: 1099000, images: ["assets/m121.webp","assets/m122.webp"], description: "Co giãn tốt, form slim tôn dáng." },
  { id: 13, name: "Áo thun nam cổ tròn đen", gender: "male", category: "top", price: 299000,colorIds:["do","den","xanh","xam"],    images: ["assets/image/m4.jpg"], description: "Cotton 100%, mặc mát cả ngày." },
  { id: 14, name: "Quần tây nam slim fit đen", gender: "male", category: "bottom", price: 799000,colorIds:["den","xam","nau"],    oldPrice: 1099000, images: ["assets/image/m3.jpg"], description: "Co giãn tốt, form slim tôn dáng." },
];
